src/Entity/Company.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Company.
 */
#[ORM\Table(name: 'company', options: ['collate' => 'utf8mb4_unicode_520_ci'])]
#[ORM\Entity]
#[UniqueEntity('nameFull')]
class Company
{
    /**
     * @var int
     */
    #[ORM\Column(name: 'id', type: 'integer', nullable: false)]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private $id;

    /**
     * @var string
     */
    #[ORM\Column(name: 'name_full', type: 'string', length: 511, nullable: false, unique: true, options: ['collation' => 'utf8mb4_bin'])]
    private $nameFull;

    /**
     * @var string
     */
    #[ORM\Column(name: 'name', type: 'string', length: 511, nullable: false)]
    private $name;

    /**
     * @var string|null
     */
    #[ORM\Column(name: 'description', type: 'string', length: 511, nullable: true)]
    private $description;

    /**
     * @var array|null
     */
    #[ORM\Column(name: 'info_by_year', type: 'json', nullable: true)]
    private $infoByYear;

    /**
     * @var Collection<PersonCompany>
     */
    #[ORM\OneToMany(targetEntity: PersonCompany::class, mappedBy: 'company', cascade: ['persist'], fetch: 'EAGER')]
    public Collection $personRelations;

    public function __construct()
    {
        $this->personRelations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setName($name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setFullname($nameFull): self
    {
        $this->nameFull = $nameFull;

        return $this;
    }

    public function getFullname(): string
    {
        return $this->nameFull;
    }

    public function setInfoByYear($info, $year = null): self
    {
        if (is_null($year)) {
            $this->infoByYear = $info;
        }
        else {
            if (is_null($this->infoByYear)) {
                $this->infoByYear = [];
            }

            $this->infoByYear[$year] = $info;
        }

        return $this;
    }

    public function getInfoByYear($year = null): ?array
    {
        if (is_null($year)) {
            return $this->infoByYear;
        }

        return $this->infoByYear[$year] ?? null;
    }

    public function addPersonRelation(PersonCompany $personCompany): self
    {
        $this->personRelations[] = $personCompany;

        return $this;
    }

    public function getPersonRelations(?bool $isBoard = null): iterable
    {
        if (is_null($isBoard)) {
            return $this->personRelations;
        }

        return $this->personRelations->filter(function (PersonCompany $personCompany) use ($isBoard) {
            return $personCompany->getIsBoard() === $isBoard;
        });
    }
}

src/Controller/CompanyController.php
<?php

// src/Controller/CompanyController.php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Spiriit\Bundle\FormFilterBundle\Filter\FilterBuilderUpdater;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Routing\Attribute\Route;
use App\Filter\CompanyFilterType;
use App\Entity\Company;
use App\Entity\Person;

class CompanyController extends AbstractController
{
    protected const PAGE_LIMIT = 100;

    #[Route('/company', name: 'company_list')]
    public function listAction(
        Request $request,
        FormFactoryInterface $formFactory,
        EntityManagerInterface $em,
        FilterBuilderUpdater $filterBuilderUpdater,
        PaginatorInterface $paginator
    ): Response {
        // initialize a query builder
        $filterBuilder = $em
            ->getRepository(Company::class)
            ->createQueryBuilder('c')
            ->select('c, c.name AS name, COUNT(pc) AS numPersons')
            ->leftJoin('c.personRelations', 'pc')
            ->groupBy('c.id')
        ;

        $form = $formFactory->create(CompanyFilterType::class);

        if ($request->query->has($form->getName())) {
            // manually bind values from the request
            $form->submit($request->query->all()[$form->getName()]);

            // build the query from the given form object
            $filterBuilderUpdater->addFilterConditions($form, $filterBuilder);
        }

        $pagination = $paginator->paginate(
            $filterBuilder->getQuery(),
            $request->query->get('page', 1),
            self::PAGE_LIMIT,
            [
                'defaultSortFieldName' => 'name',
                'defaultSortDirection' => 'asc',
            ]
        );

        return $this->render('Company/list.html.twig', [
            'form' => $form->createView(),
            'pagination' => $pagination,
        ]);
    }

    protected function findSimilar(EntityManagerInterface $em, Company $entity)
    {
        $dbconn = $em->getConnection();

        // build all the ids
        $person_ids = [];
        foreach ($entity->getPersonRelations() as $personCompany) {
            $person_ids[] = $personCompany->getPerson()->getId();
        }

        $num_persons = count($person_ids);
        if (0 == $num_persons) {
            return $person_ids;
        }

        $querystr = 'SELECT person_id, company_id'
            . ' FROM person_company'
            . ' WHERE person_id IN (' . join(', ', $person_ids) . ')'
            . ' AND company_id <> ' . $entity->getId()
            . ' ORDER BY company_id';

        $persons_by_company = [];
        $stmt = $dbconn->executeQuery($querystr);
        while ($row = $stmt->fetchAssociative()) {
            if (!array_key_exists($row['company_id'], $persons_by_company)) {
                $persons_by_company[$row['company_id']] = [];
            }

            // avoid duplicates
            if (in_array($row['person_id'], $persons_by_company[$row['company_id']])) {
                continue;
            }

            $persons_by_company[$row['company_id']][] = $row['person_id'];
        }

        $jaccard_index = [];
        $company_ids = array_keys($persons_by_company);
        if (count($company_ids) > 0) {
            $querystr = 'SELECT name, company_id, COUNT(DISTINCT person_id) AS num_persons'
                . ' FROM person_company'
                . ' LEFT OUTER JOIN company ON person_company.company_id=company.id'
                . ' WHERE company_id IN (' . join(', ', $company_ids) . ')'
                . ' GROUP BY company_id';
            $stmt = $dbconn->executeQuery($querystr);
            while ($row = $stmt->fetchAssociative()) {
                $num_shared = count($persons_by_company[$row['company_id']]);
                $jaccard_index[$row['company_id']] = [
                    'name' => $row['name'],
                    'count' => $num_shared,
                    'coefficient' => 1.0
                        * $num_shared // shared
                        / ($row['num_persons'] + $num_persons - $num_shared),
                ];
            }

            uasort(
                $jaccard_index,
                function ($a, $b) {
                    if ($a['coefficient'] == $b['coefficient']) {
                        return 0;
                    }

                    // highest first
                    return $a['coefficient'] < $b['coefficient'] ? 1 : -1;
                }
            );
        }

        return $jaccard_index;
    }

    #[Route('/company/{id}', name: 'company_show')]
    public function detailAction(
        int $id,
        EntityManagerInterface $em
    ): Response {
        $entity =  $em->getRepository(Company::class)->find($id);
        if (is_null($entity)) {
            throw $this->createNotFoundException('Company not found');
        }

        return $this->render('Company/detail.html.twig', [
            'company' => $entity,
            'similar' => $this->findSimilar($em, $entity),
        ]);
    }

    #[Route('/company/shared/{persons}', name: 'company_shared')]
    public function sharedAction(
        Request $request,
        EntityManagerInterface $em,
        PaginatorInterface $paginator,
        $persons = null
    ) {
        if (!is_null($persons)) {
            $persons = explode(',', $persons);
        }

        if (is_null($persons) || count($persons) < 2) {
            throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Invalid argument');
        }

        $entities = [];
        $names = [];
        $personRepo = $em->getRepository(Person::class);
        for ($i = 0; $i < 2; ++$i) {
            $criteria = new \Doctrine\Common\Collections\Criteria();

            $criteria->where($criteria->expr()->eq('id', $persons[$i]));

            $matching = $personRepo->matching($criteria);
            if (0 == count($matching)) {
                throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Invalid argument');
            }

            $entity = $matching[0];
            $entities[] = $entity;
            $names[] = $entity->getName();
        }

        $qb = $em
                ->createQueryBuilder();

        $qb->select([
            'C',
            'C.name AS name',
        ])
            ->from('App\Entity\Company', 'C')
            ->innerJoin(
                'App\Entity\PersonCompany',
                'PC1',
                \Doctrine\ORM\Query\Expr\Join::WITH,
                'PC1.company = C AND PC1.person = :person1'
            )
            ->innerJoin(
                'App\Entity\PersonCompany',
                'PC2',
                \Doctrine\ORM\Query\Expr\Join::WITH,
                'PC2.company = C AND PC2.person = :person2'
            )
            ->setParameter('person1', $entities[0])
            ->setParameter('person2', $entities[1])
            ->groupBy('C.id')
            ->orderBy('name')
        ;

        $pagination = $paginator->paginate(
            $qb->getQuery(),
            $request->query->get('page', 1),
            self::PAGE_LIMIT,
            [
                'defaultSortFieldName' => 'name',
                'defaultSortDirection' => 'asc',
            ]
        );

        return $this->render('Company/shared.html.twig', [
            'pageTitle' => 'Gemeinsame Firmen von'
                . ' ' . implode(' und ', $names),
            'pagination' => $pagination,
        ]);
    }
}

templates/Company/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1>{{ company.name }}</h1>
{% for year, info in company.infoByYear %}
    {#<h2>{{ year }}</h2>#}
    <div>
        {% if info.osmID is defined %}
        <a href="{{ path('place_show', { 'osmID': info.osmID }) }}">
            {% if info.placeNameGeocoded is empty %}
                -- ohne Ortsname --
            {% else %}
                {{ info.placeNameGeocoded }}
            {% endif %}
        </a>
        {% endif %}
        {% if company.personRelations|length > 0 %}
            {% for isBoard,label in { 1: 'Aufsichtsrat', 0: 'Vorstand',  } %}
                {% set personRelations = company.personRelations(isBoard == true) %}
                {% if personRelations|length > 0 %}
                <h3>{{ label }}</h3>
                <ul>
                    {% for personRelation in personRelations %}
                        <li>
                            <a href="{{ path('person_show', { 'id': personRelation.person.id }) }}">{{ personRelation.person.fullname }}</a>
                            ({{ personRelation.relationship }}, {{ personRelation.person.companyRelations|length }})
                        </li>
                    {% endfor %}
                </ul>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if similar|length > 0 %}
        <h3>Personell verbundene Firmen</h3>
        <ul>
            {% for id,related in similar %}
                <li>
                    <a href="{{ path('company_show', { 'id': id }) }}">{{ related.name }}</a>
                    (<a href="{{ path('person_shared', { 'companies': [ company.id, id ]|join(',') }) }}" data-remote="false" data-bs-toggle="modal" data-bs-target="#detailModal">{{ related.count }}, {{ (100 * related.coefficient)|round(1) }}%</a>)
                </li>
            {% endfor %}
        </ul>

        <!-- Modal for shared Person -->
        <div id="detailModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>Loading....</p>
                    </div>
                </div>
            </div>
        </div>
        <script>
        document.addEventListener("DOMContentLoaded", function(event) {
            // Your code to run since DOM is loaded and ready
            $('#detailModal').on('show.bs.modal', function(e) {
                var link = $(e.relatedTarget);
                $(this).find('.modal-body').html('Loading...');
                $(this).find('.modal-body').load(link.attr('href'));
            });
        });
        </script>
        {% endif %}
    </div>
{% endfor %}

{% endblock %}

templates/Company/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1>Firmen</h1>
<form method="get" action="{{ path(app.request.attributes.get('_route')) }}">
    <div class="form-group">
        {{ form_rest(form) }}
        {#<button type="submit" class="btn btn-primary">{{ 'Search'|trans }}</button>#}
    </div>
</form>
<div class="d-flex flex-row mb-3">
    <div>Sortieren</div>
    <div class="ms-2"{% if pagination.isSorted('name') %} style="font-weight: bold"{% endif %}>{{ knp_pagination_sortable(pagination, 'Name', 'name', {}, {'direction': 'asc'}) }}</div>
    <div class="ms-2"{% if pagination.isSorted('numPersons') %} style="font-weight: bold"{% endif %}>{{ knp_pagination_sortable(pagination, 'Anzahl Personen', 'numPersons', {}, {'direction': 'desc'}) }}</div>
</div>
{% for row in pagination %}
    {% set company = row[0] %}
    <div>
        <a href="{{ path('company_show', { 'id': company.id }) }}">{{ company.fullName }}</a>
        ({{ row['numPersons'] }})
    </div>
{% endfor %}

{# display navigation #}
<div class="navigation">
    {{ knp_pagination_render(pagination) }}
</div>

{% endblock %}

templates/Company/shared.html.twig
{% block body %}

<h3>{{ pageTitle }}</h3>

{% for row in pagination %}
    {% set company = row[0] %}
    <div>
        <a href="{{ path('company_show', { 'id': company.id }) }}">{{ company.fullName }}</a>
        ({{ company.personRelations|length }})
    </div>
{% endfor %}

{% endblock %}